### PR TITLE
Initial build hooks draft

### PR DESCRIPTION
**Pull request by learn-more**
This is a draft because I just took a wild stab at this feature, and I have no clue if this is even remotely what you were thinking about.

Using the provided code, and this `build.lua` results in a fused game with compiled lua files in it:

```lua

return {
    -- basic settings:
    name = 'Plinko',                    -- name of the game for your executable
    developer = 'Mark Jansen',          -- dev name used in metadata of the file
    output = 'dist',                    -- output location for your game, defaults to $SAVE_DIRECTORY
    version = '1.1a',                   -- 'version' of your game, used to name the folder in output
    love = '12.0',                      -- version of LÖVE to use, must match github releases
    ignore = { 'dist', '.gitkeep' },    -- folders/files to ignore in your project
    icon = 'assets/icon.png',           -- 256x256px PNG icon for game, will be converted for you

    -- optional settings:
    use32bit = false,                     -- set true to build windows 32-bit as well as 64-bit
    identifier = 'com.markjansen.plinko',   -- macos team identifier, defaults to game.developer.name
    --libs = {                              -- files to place in output directly rather than fuse
        --windows = { 'resources/plugin.dll' }, -- can specify per platform or "all"
        --all = { 'resources/license.txt' }
    --},
    platforms = { 'windows' }, -- set if you only want to build for a specific platform

    hooks = {
        pre_lovefile = function(zip)
            -- Store the original function
            local original_add = zip['_add']
            -- Substitute our own function
            zip['_add'] = function(self, filename, content, extraattr, modtime)
                -- Is this a filename that ends with .lua ?
                if string.match(filename, '[.]lua$') then
                    love.build.log(' (c)-> ' .. tostring(filename))
                    -- Load the lua code
                    local lua_data = assert(load(content))
                    -- Convert to bytecode, strip debug symbols
                    content = assert(string.dump(lua_data, true))
                else
                    love.build.log(' ( )-> ' .. tostring(filename))
                end
                -- Call the original '_add' function
                return original_add(self, filename, content, extraattr, modtime)
            end
        end,
        post_lovefile = function(output_zip)
            love.build.log('post_lovefile:' .. tostring(output_zip))
        end,
        pre_build = function(zip)
            local original_add = zip['_add']
            zip['_add'] = function(self, filename, content, extraattr, modtime)
                love.build.log(' -> ' .. tostring(filename))
                return original_add(self, filename, content, extraattr, modtime)
            end
        end,
        post_build = function(output_zip)
            love.build.log('post_build:' .. tostring(output_zip))
        end,
    }
}
```

[build.log](https://github.com/user-attachments/files/15828987/build.log)

There are some issues with it, for example when `love-build` is running in a love.exe of a different architecture than the target one, the compiled lua code will not load.

### CODE REVIEW

**Comment by ellraiser** [comment]
Thanks for this! I don't think I like the idea of logic inside `build.lua`, and not sure lua is the best option for all devs when it comes to devops

I think for the general pre/post hook feature I'm thinking to just let people specify a bash file or just a cmd to run - either for `all` or a specific OS like the config already does for lib files, and then run that before/after using os.execute. Then I can just give people like a %OUTPUT% variable that they can pass to the bash/cmd to use (or whatever other arguments are useful)

I think that'd give more flexibility as you can then do other terminal stuff rather than being limited by just lua

```lua
hooks = {
  before = {
    all = 'prebuild.sh',
    windows = 'setup.sh arch=%ARCH%'
  },
  after = {
    all = 'postbuild.sh output=%OUTPUT%',
  }
}
```

**Comment by learn-more** [comment]
> Thanks for this! I don't think I like the idea of logic inside `build.lua`, and not sure lua is the best option for all devs when it comes to devops
> 
> I think for the general pre/post hook feature I'm thinking to just let people specify a bash file or just a cmd to run - either for `all` or a specific OS like the config already does for lib files, and then run that before/after using os.execute. Then I can just give people like a %OUTPUT% variable that they can pass to the bash/cmd to use (or whatever other arguments are useful)
> 
> I think that'd give more flexibility as you can then do other terminal stuff rather than being limited by just lua
> 
> ```lua
> hooks = {
>   before = {
>     all = 'prebuild.sh',
>     windows = 'setup.sh arch=%ARCH%'
>   },
>   after = {
>     all = 'postbuild.sh output=%OUTPUT%',
>   }
> }
> ```

I'd argue that this is more limiting actually, since my example (precompiling lua files) won't work in the current design, and if you want to execute a process, you can always `os.execute` in a hook to run a process.


(The precompiling lua files not being possible with a shell script is mainly a limitation of how zipping the files works, globbing and compressing files inside the zip class.)

**Comment by ellraiser** [comment]
My assumption here though is you're not including build files in your actual project, so if you just have "process.lua" at the root of your project then the builder should just be able to load + run that file no problems during the process?

**Comment by learn-more** [comment]
> My assumption here though is you're not including build files in your actual project, so if you just have "process.lua" at the root of your project then the builder should just be able to load + run that file no problems during the process?

But to pre-process files before they are put inside the .love file, you'd need to copy all files to another directory, edit them there and then modify the build.lua to use that as game root directory.

**Comment by ellraiser** [comment]
I don't think I really understand the use-case you're thinking of here, especially cos we already have the entire project mounted and so can modify whatever we need, but either way I don't think this PR is quite what I'm thinking of yet but appreciate you taking a stab at it - I'll be looking at doing some more stuff with love-build soonish and will do some stuff towards the hooks functionality and then can take it from there as people try and use it for their own live build processes

**Pull request closed without merging**
