### PR TITLE
Add export location of linux specific libraries to LUA_CPATH

### PR DESCRIPTION
**Pull request by Endaris**
Thanks again for your huge patience and support.
This is the solution that works for me without having to add any extra code for the linux distribution inside the exported project itself.
I'm not sure if `$APPDIR/lib/lua/5.1/?.so` couldn't also get removed from LUA_CPATH as there never seems to be a `lua` directory within `lib` but I'm not familiar enough with lua distribution so I kept it.
I modified the linux workflow to use the `AppRun` generated by love-build in place of the love 12 appimage as the latter will find https for obvious reasons.
In the process I eliminated copying the `.DirIcon` as linux automatically generates one during the unzip process and you will always get an overwrite prompt which both disrupts the workflow and is actually a bit annoying for linux users trying to extract and it does not impact icon display.
I'm not sure what exactly causes it but the moment I unzip or compress into an .AppImage, a link to icon.png is created at `.DirIcon` so the compressed result always has the correct icon for me even without explicitly creating one in the build step. Alternatively we could only write it if the OS is not linux but ultimately this would be solved by love-build directly compressing into an AppImage.

Workflow run on my fork: https://github.com/Endaris/love-build/actions/runs/8853171216/job/24313412862

### CODE REVIEW

**Comment by ellraiser** [comment]
Few things with this:
- I want to keep the .dirIcon stuff, 1. because eventually it'll be used in the actual AppImage export option and 2. because I don't get the unzip error you mentioned on Ubuntu 20.04 and 22.04 so feels like a linux flavour specific issue

- Changing the CPATH in the AppRun is a nice idea - does this pick up the library files correctly inside the final /lib/ folder without the need to change the package.cpath then?

- I'm still undecided on whether to output the files to /lib or /bin, if it was /bin then at least it would be "consistent" across platforms that the files are always put in the location that LOVE classes as the "source base directory". MacOS doesn't have an option like linux does so will still have to have the package.cpath example in the example project sadly but eh

- Good catch on using 12 to run in the workflow, however as this is cross-platform if you're updating the workflow would be best to match the changes on all 3 platforms not just linux (i.e. unzip and run for both mac + windows). ~~Also not sure why the change to 7z outside of just... personal preference?~~ ignore me I'm just blind! :D

**Comment by ellraiser** [comment]
Have updated windows/macos to match what you've done for linux in the workflow, so if you could pull latest and remove the .dirIcon change for now I can merge later - can decide on the /lib vs /bin stuff later, main thing is having it working first

**Comment by Endaris** [comment]
Hmm, that's kind of odd, when the workflow ran on my repo [it threw an error](https://github.com/Endaris/love-build/actions/runs/8853067919/job/24313089510).
I'll readd it and then we'll see later.

> Changing the CPATH in the AppRun is a nice idea - does this pick up the library files correctly inside the final /lib/ folder without the need to change the package.cpath then?

It does!

**Comment by ellraiser** [comment]
Hmm strange - doesn't happen on a real Ubuntu machine so not sure why the runner is having an issue, but deffo don't want to remove that file (also looks like it's not the same file as it wants to use "./.DirIcon" to replace ".DirIcon" so might just be some crap leftover from the rest of the workflow)

Could prob just modify the 7z command to say yes for you, think it's just a `-y` flag?

**Comment by Endaris** [comment]
Yep that works!
Earlier I had the ls -a to verify that there was indeed still a .DirIcon so I removed that.

**Comment by ellraiser** [comment]
Nice one! Thanks - will do a new release later so the AppRun change is put in

**Pull request merged**
